CREATE TABLE IF NOT EXISTS company_state(id INTEGER PRIMARY KEY CHECK(id=1),version INTEGER NOT NULL,snapshot_json TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS brain_events(id TEXT PRIMARY KEY,at TEXT NOT NULL,type TEXT NOT NULL,source TEXT NOT NULL,payload_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS decisions(id TEXT PRIMARY KEY,at TEXT NOT NULL,record_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS checkpoints(id INTEGER PRIMARY KEY CHECK(id=1),run_id TEXT NOT NULL,stage TEXT NOT NULL,state_version INTEGER NOT NULL,snapshot_json TEXT NOT NULL,at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS runs(run_id TEXT PRIMARY KEY,idempotency_key TEXT NOT NULL UNIQUE,stage TEXT NOT NULL,status TEXT NOT NULL,snapshot_json TEXT NOT NULL,started_at TEXT NOT NULL,updated_at TEXT NOT NULL);
