import type {BrainRepository} from "./repository.ts";import type {BrainEvent,Checkpoint,CompanyState,Decision,Run} from "./contracts.ts";
type Row=Record<string,unknown>;export interface D1Stmt{bind(...v:unknown[]):D1Stmt;first<T=Row>():Promise<T|null>;run():Promise<{meta?:{changes?:number}}>}export interface D1{prepare(sql:string):D1Stmt}
export class D1BrainRepository implements BrainRepository{constructor(private db:D1){}
async loadState(){const r=await this.db.prepare("SELECT snapshot_json FROM company_state WHERE id=1").first<{snapshot_json:string}>();return r?JSON.parse(r.snapshot_json):null}
async saveState(n:CompanyState,e:number){const r=await this.db.prepare("UPDATE company_state SET version=?,snapshot_json=?,updated_at=? WHERE id=1 AND version=?").bind(n.version,JSON.stringify(n),n.updatedAt,e).run();if(!r.meta?.changes)throw new Error("STATE_VERSION_CONFLICT")}
async seedState(n:CompanyState){await this.db.prepare("INSERT OR IGNORE INTO company_state(id,version,snapshot_json,updated_at) VALUES(1,?,?,?)").bind(n.version,JSON.stringify(n),n.updatedAt).run()}
async appendEvent(e:BrainEvent){await this.db.prepare("INSERT OR IGNORE INTO brain_events(id,at,type,source,payload_json) VALUES(?,?,?,?,?)").bind(e.id,e.at,e.type,e.source,JSON.stringify(e.payload)).run()}
async appendDecision(d:Decision){await this.db.prepare("INSERT OR IGNORE INTO decisions(id,at,record_json) VALUES(?,?,?)").bind(d.id,d.at,JSON.stringify(d)).run()}
async loadCheckpoint(){const r=await this.db.prepare("SELECT snapshot_json FROM checkpoints WHERE id=1").first<{snapshot_json:string}>();return r?JSON.parse(r.snapshot_json):null}
async saveCheckpoint(c:Checkpoint,e:number){const s=await this.loadState();if(!s||s.version!==e)throw new Error("CHECKPOINT_STATE_VERSION_CONFLICT");await this.db.prepare("INSERT INTO checkpoints(id,run_id,stage,state_version,snapshot_json,at) VALUES(1,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET run_id=excluded.run_id,stage=excluded.stage,state_version=excluded.state_version,snapshot_json=excluded.snapshot_json,at=excluded.at").bind(c.runId,c.stage,c.stateVersion,JSON.stringify(c),c.at).run()}
async findRunByIdempotencyKey(k:string){const r=await this.db.prepare("SELECT snapshot_json FROM runs WHERE idempotency_key=?").bind(k).first<{snapshot_json:string}>();return r?JSON.parse(r.snapshot_json):null}
async saveRun(r:Run){await this.db.prepare("INSERT INTO runs(run_id,idempotency_key,stage,status,snapshot_json,started_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(run_id) DO UPDATE SET stage=excluded.stage,status=excluded.status,snapshot_json=excluded.snapshot_json,updated_at=excluded.updated_at").bind(r.runId,r.idempotencyKey,r.stage,r.status,JSON.stringify(r),r.startedAt,r.updatedAt).run()}
}