# Client-facing content for the VIIVERSION product site.
# Keep marketing copy here; templates and rendering belong in build-product-site.py.

LANGS = ("ru", "en")

BRAND = {
    "ru": {
        "tagline": "Цифровые системы для продаж и операций",
        "hero_title": "Цифровые решения для конкретных задач бизнеса.",
        "hero_lead": "Настраиваем онлайн-бронирование, клиентские приложения, CRM, AI-консультантов, оплату и интеграции. Можно начать с одной задачи и не менять то, что уже работает.",
        "hero_primary": "Выбрать свою отрасль",
        "hero_secondary": "Посмотреть рабочие демо",
        "problem_title": "Что сейчас тормозит процесс?",
        "problem_lead": "Начинаем не с набора технологий, а с одного участка, где теряется время, заявки или данные.",
        "products_title": "Основные продукты",
        "products_lead": "Каждый продукт решает самостоятельную задачу и при необходимости соединяется с другими.",
        "proof_title": "Посмотрите, что мы уже собрали",
        "proof_lead": "Показываем не только интерфейс, но и сценарий: что делает клиент, что получает команда и какие части уже реализованы.",
        "start_title": "Начните с одной небольшой задачи",
        "start_lead": "Фиксированный первый шаг проще согласовать и проверить. Если он даёт результат, расширяем систему дальше.",
        "matrix_title": "Один продукт — разные сценарии для разных отраслей",
        "matrix_lead": "Выберите продукт и посмотрите, где он применим. Сама технология остаётся знакомой, а сценарий меняется под процесс бизнеса.",
        "special_title": "Для партнёров и сложных внутренних систем",
        "team_title": "Вы общаетесь напрямую с теми, кто делает продукт",
        "final_title": "Покажите, как задача решается у вас сейчас.",
        "final_lead": "Предложим конкретный первый шаг, заранее зафиксируем что входит, срок и ориентир по стоимости. Рабочие системы не меняем без необходимости.",
    },
    "en": {
        "tagline": "Digital systems for sales and operations",
        "hero_title": "Automate sales and operations — from one process to a connected system.",
        "hero_lead": "Booking, customer apps, CRM, AI, payments and integrations. Start with one module or connect several without replacing everything that already works.",
        "hero_primary": "Find a solution for my problem",
        "hero_secondary": "See working demos",
        "problem_title": "Where is the process breaking today?",
        "problem_lead": "We start with one point where time, leads or data are being lost — not with a shopping list of technologies.",
        "products_title": "Core products",
        "products_lead": "Each product solves a useful problem on its own and can connect to the rest when needed.",
        "proof_title": "Working demos and prototypes",
        "proof_lead": "We show the customer flow, team workflow and what is already implemented — not just interface screenshots.",
        "start_title": "Start with one small, testable task",
        "start_lead": "A fixed first step is easier to approve and verify. If it works, the system can grow from there.",
        "matrix_title": "One product, different industry scenarios",
        "matrix_lead": "Choose a product and see where it fits. The core technology stays familiar while the workflow changes around the business.",
        "special_title": "For partners and complex internal systems",
        "team_title": "Engineering and product design in one team",
        "final_title": "Show us one process you want to improve.",
        "final_lead": "We will map the current flow, propose the smallest useful change and tell you what is worth building first.",
    },
}

PRODUCTS = {
    "online-sales": {
        "ru": {
            "name": "Онлайн-продажи",
            "label": "Сайт, каталог и клиентский интерфейс",
            "headline": "Сайт, Mini App или каталог, который ведёт клиента к понятному действию.",
            "summary": "Показываем предложение, помогаем выбрать, собираем нужные параметры и передаём заявку или заказ дальше без лишней переписки.",
            "before": ["клиент ищет цену в переписке", "заявки приходят из разных каналов", "менеджер вручную уточняет одни и те же данные"],
            "after": ["клиент видит предложение и условия", "система собирает нужные параметры", "заявка сразу приходит в понятном формате"],
            "modules": [
                ("Лендинг / сайт", "Один понятный путь от предложения до заявки или покупки."),
                ("Telegram Mini App", "Каталог, услуги, профиль или заявка внутри Telegram."),
                ("Zalo Mini App", "Локальный клиентский сценарий для рынка Вьетнама."),
                ("Каталог и цены", "Клиент видит варианты и стоимость до разговора с менеджером."),
                ("Клиентский кабинет", "История, статусы и повторные действия в одном месте."),
            ],
            "price": "от 2.5M ₫ за landing; Mini App — 10–12M ₫ за типовой первый запуск",
            "timeline": "от 7–10 дней для типового Mini App",
            "offer": "mini-app-pilot",
            "proof": ["uniq-smart-rent", "ave-dental", "g-beauty", "true-surf"],
            "cta": "Получить оценку клиентского сценария",
        },
        "en": {
            "name": "Online Sales",
            "label": "Customer journey",
            "headline": "A website, Mini App or catalogue that moves the customer to a clear next action.",
            "summary": "Present the offer, help the customer choose, collect the right parameters and hand a structured lead or order to the team.",
            "before": ["customers ask for prices in chat", "leads arrive through disconnected channels", "staff repeatedly collect the same details"],
            "after": ["customers see the offer and terms", "the system collects the required inputs", "the team receives a structured lead"],
            "modules": [
                ("Landing / website", "One clear path from offer to action."),
                ("Telegram Mini App", "Catalogue, services, profile or order flow inside Telegram."),
                ("Zalo Mini App", "A local customer flow for the Vietnam market."),
                ("Catalogue & pricing", "Customers see options and pricing before talking to staff."),
                ("Customer account", "History, status and repeat actions in one place."),
            ],
            "price": "from 2.5M ₫ for a landing; typical Mini App pilot 10–12M ₫",
            "timeline": "from 7–10 days for a typical Mini App pilot",
            "offer": "mini-app-pilot",
            "proof": ["uniq-smart-rent", "ave-dental", "g-beauty", "true-surf"],
            "cta": "Get a scope for my customer flow",
        },
    },
    "booking": {
        "ru": {
            "name": "Онлайн-бронирование",
            "label": "Бронирование и расписание",
            "headline": "Бронирование без длинной переписки с менеджером.",
            "summary": "Клиент выбирает услугу, дату и параметры сам. Команда получает полный заказ, а не цепочку сообщений, которую ещё нужно собирать вручную.",
            "before": ["клиент спрашивает о свободной дате", "менеджер проверяет таблицу или чат", "цена и параметры уточняются в нескольких сообщениях", "бронь переносится вручную"],
            "after": ["клиент выбирает дату и параметры", "система рассчитывает или показывает условия", "бронь создаётся в структурированном виде", "команда получает готовый заказ"],
            "modules": [
                ("Модуль бронирования", "Собирает услугу, дату, количество и дополнительные параметры."),
                ("Расписание", "Показывает доступные даты и слоты."),
                ("Каталог и цены", "Связывает бронирование с услугой и тарифом."),
                ("Подтверждения", "Отправляет клиенту и команде статус брони."),
                ("Напоминания", "Автоматически напоминает о предстоящей услуге."),
            ],
            "price": "8–18M ₫ за базовый Booking Start",
            "timeline": "ориентир 7–14 дней для одного законченного сценария",
            "offer": "booking-start",
            "proof": ["max-tour", "ave-dental", "pet-nika", "true-surf"],
            "cta": "Получить оценку Booking для моего процесса",
        },
        "en": {
            "name": "Booking",
            "label": "Booking & scheduling",
            "headline": "Booking without a long back-and-forth with staff.",
            "summary": "The customer chooses the service, date and parameters. The team receives a complete structured booking instead of reconstructing it from messages.",
            "before": ["the customer asks about availability", "staff check a spreadsheet or chat", "price and details are clarified over several messages", "the booking is copied manually"],
            "after": ["the customer selects date and parameters", "the system shows price or terms", "a structured booking is created", "the team receives a complete order"],
            "modules": [
                ("Booking Engine", "Collects service, date, quantity and options."),
                ("Schedule", "Shows available dates and slots."),
                ("Catalogue & pricing", "Connects the booking to a service and tariff."),
                ("Confirmations", "Sends booking status to customer and team."),
                ("Reminders", "Automatically reminds the customer before the service."),
            ],
            "price": "8–18M ₫ for a basic Booking Start",
            "timeline": "typically 7–14 days for one complete booking flow",
            "offer": "booking-start",
            "proof": ["max-tour", "ave-dental", "pet-nika", "true-surf"],
            "cta": "Get a Booking scope for my process",
        },
    },
    "operations": {
        "ru": {
            "name": "CRM и работа команды",
            "label": "Заявки, заказы и рабочая панель",
            "headline": "Клиенты, заказы и работа команды — в одной системе.",
            "summary": "CRM, рабочая панель, статусы и аналитика собираются вокруг реального процесса бизнеса — без переноса данных между отдельными таблицами и чатами.",
            "before": ["лиды и заказы разбросаны по чатам", "сотрудники держат следующий шаг в голове", "статусы обновляются вручную", "руководитель не видит общую картину"],
            "after": ["единая очередь клиентов и заказов", "понятные статусы и ответственные", "операции ведутся из одной панели", "руководитель видит ключевые показатели"],
            "modules": [
                ("CRM", "Лиды, история, статус и следующий шаг."),
                ("Рабочая панель", "Заказы, расписание, каталог и рабочие действия команды."),
                ("Панель руководителя", "Ключевые показатели и очередь для руководителя."),
                ("Аналитика", "Источники, конверсия, загрузка и скорость обработки."),
                ("Повторные продажи", "Напоминания и возврат клиентов по истории."),
            ],
            "price": "15–35M ₫ за CRM Core или Back-office Core",
            "timeline": "ориентир 2–4 недели для первого рабочего контура",
            "offer": "operations-core",
            "proof": ["max-tour", "pet-nika", "rusinfocenter"],
            "cta": "Разобрать текущий процесс",
        },
        "en": {
            "name": "Operations",
            "label": "CRM & back office",
            "headline": "Customers, orders and team work in one operating flow.",
            "summary": "CRM, back office, status and analytics are organised around how the business actually works instead of another isolated spreadsheet.",
            "before": ["leads and orders are scattered across chats", "staff keep the next step in their heads", "statuses are updated manually", "management lacks a single view"],
            "after": ["one queue for customers and orders", "clear status and ownership", "operations run from one workspace", "management sees the key numbers"],
            "modules": [
                ("CRM", "Lead history, status and next action."),
                ("Back office", "Orders, schedule, catalogue and team actions."),
                ("Owner Dashboard", "Key indicators and management queue."),
                ("Analytics", "Sources, conversion, load and SLA."),
                ("Repeat Sales", "Reminders and reactivation based on customer history."),
            ],
            "price": "15–35M ₫ for CRM Core or Back-office Core",
            "timeline": "typically 2–4 weeks for the first working operating flow",
            "offer": "operations-core",
            "proof": ["max-tour", "pet-nika", "rusinfocenter"],
            "cta": "Map my current workflow",
        },
    },
    "ai-operator": {
        "ru": {
            "name": "AI-консультант",
            "label": "AI для продаж и поддержки",
            "headline": "AI-консультант, который знает ваш продукт и ведёт клиента к следующему действию.",
            "summary": "Отвечает только в согласованном контуре, уточняет запрос, подбирает подходящий вариант и передаёт контекст в заявку, бронирование или CRM.",
            "before": ["менеджеры отвечают на повторяющиеся вопросы", "клиенту трудно выбрать из большого каталога", "ночные обращения ждут утра", "контекст теряется при передаче человеку"],
            "after": ["AI отвечает по утверждённой базе знаний", "уточняет параметры и помогает выбрать", "передаёт структурированный контекст", "сложные запросы уходят человеку"],
            "modules": [
                ("AI-консультант", "Отвечает на вопросы и уточняет запрос."),
                ("AI-поиск", "Подбирает услугу, тур, объект или товар по обычному запросу клиента."),
                ("Рекомендации", "Сужает выбор по параметрам клиента."),
                ("Передача менеджеру", "Передаёт менеджеру контекст, а не пустой контакт."),
                ("Автоматизация действий", "Запускает согласованные действия после консультации."),
            ],
            "price": "8–25M ₫ за типовой AI Consultant",
            "timeline": "ориентир 7–14 дней для одного канала и одной задачи",
            "offer": "ai-operator-pilot",
            "proof": ["max-tour"],
            "cta": "Показать AI на моём сценарии",
        },
        "en": {
            "name": "AI Operator",
            "label": "AI for sales & support",
            "headline": "An AI assistant that knows your offer and moves the customer to the next action.",
            "summary": "It answers within an approved scope, clarifies the request, recommends an option and passes context into a lead, booking or CRM.",
            "before": ["staff answer the same questions repeatedly", "customers struggle with a large catalogue", "after-hours enquiries wait until morning", "context is lost when handed to a person"],
            "after": ["AI answers from an approved knowledge base", "clarifies the request and helps choose", "passes structured context to the team", "complex cases escalate to a person"],
            "modules": [
                ("AI Consultant", "Answers questions and clarifies intent."),
                ("AI Search", "Finds services, tours, properties or products from natural-language requests."),
                ("Recommendations", "Narrows the options around customer parameters."),
                ("Lead Handoff", "Passes context instead of an empty contact."),
                ("Workflow Automation", "Triggers approved actions after the conversation."),
            ],
            "price": "8–25M ₫ for a typical AI Consultant",
            "timeline": "typically 7–14 days for one channel and one defined task",
            "offer": "ai-operator-pilot",
            "proof": ["max-tour"],
            "cta": "See AI on my scenario",
        },
    },
    "paybridge": {
        "ru": {
            "name": "PayBridge",
            "label": "Оплата и интеграции",
            "headline": "Связывает оплату с заказом и возвращает подтверждённый статус в вашу рабочую систему.",
            "summary": "Связывает POS, сайт или приложение с платёжным провайдером. После оплаты заказ получает подтверждённый статус там, где с ним работает команда.",
            "before": ["оплата и заказ живут в разных системах", "статус приходится проверять вручную", "webhook-события обрабатываются нестабильно", "сверка занимает время"],
            "after": ["один понятный payment flow", "подтверждённый статус возвращается в back-office", "ошибки и повторные события обрабатываются системно", "есть база для reconciliation и analytics"],
            "modules": [
                ("Подключение оплаты", "Связывает оплату с бронированием или заказом."),
                ("Связка POS и оплаты", "Связывает кассовый сценарий с платёжным провайдером."),
                ("Webhooks", "Принимает и нормализует статусы."),
                ("Сверка платежей", "Даёт основу для автоматической сверки транзакций."),
                ("API-интеграция", "Передаёт события дальше в CRM, ERP или аналитику."),
            ],
            "price": "10–30M ₫ за типовую payment integration; middleware pilot — после технического scope",
            "timeline": "срок фиксируется после проверки POS, provider API и callback flow",
            "offer": "integration-sprint",
            "proof": ["max-tour"],
            "cta": "Обсудить технический пилот",
        },
        "en": {
            "name": "PayBridge",
            "label": "Платежи и интеграционный слой",
            "headline": "Connect checkout, payment and verified status back to your business system.",
            "summary": "An integration layer between POS, website or app and the payment provider. Confirmed payment status returns to the system where the team manages the order.",
            "before": ["payment and order live in separate systems", "staff verify payment manually", "webhook events are handled inconsistently", "reconciliation takes time"],
            "after": ["one clear payment flow", "verified status returns to back office", "errors and repeat events are handled systematically", "the data is ready for reconciliation and analytics"],
            "modules": [
                ("Payment integration", "Connects payment to the booking or order flow."),
                ("POS middleware", "Connects the checkout flow to the payment layer."),
                ("Webhooks", "Receives and normalises payment events."),
                ("Reconciliation", "Provides a basis for transaction matching."),
                ("API layer", "Passes events into CRM, ERP or analytics."),
            ],
            "price": "10–30M ₫ for a typical payment integration; middleware pilot after technical scoping",
            "timeline": "timeline is set after reviewing the POS, provider API and callback flow",
            "offer": "integration-sprint",
            "proof": ["max-tour"],
            "cta": "Discuss a technical pilot",
        },
    },
}

OFFERS = {
    "booking-start": {
        "product": "booking",
        "ru": {
            "name": "Booking Start",
            "headline": "Один законченный сценарий бронирования вместо ручной переписки.",
            "scope": ["выбор услуги", "дата или слот", "ключевые параметры", "создание брони", "подтверждение клиенту и команде"],
            "price": "8–18M ₫",
            "timeline": "ориентир 7–14 дней",
            "proof": "MAX TOUR, AVE Dental, PET NIKA, TRUE SURF",
            "cta": "Получить оценку Booking Start",
        },
        "en": {
            "name": "Booking Start",
            "headline": "One complete booking flow instead of manual back-and-forth.",
            "scope": ["service selection", "date or slot", "key parameters", "booking creation", "confirmation for customer and team"],
            "price": "8–18M ₫",
            "timeline": "typically 7–14 days",
            "proof": "MAX TOUR, AVE Dental, PET NIKA, TRUE SURF",
            "cta": "Get a Booking Start estimate",
        },
    },
    "mini-app-pilot": {
        "product": "online-sales",
        "ru": {
            "name": "Mini App Pilot",
            "headline": "Один рабочий клиентский сценарий внутри Telegram — без разработки большой системы целиком.",
            "scope": ["главный экран", "каталог или услуги", "одно ключевое действие", "адаптация под мобильный сценарий", "публичная рабочая версия"],
            "price": "10–12M ₫ за типовой первый запуск",
            "timeline": "7–10 дней",
            "proof": "AVE Dental, UNIQ SMART RENT, PET NIKA, TRUE SURF",
            "cta": "Оценить Mini App Pilot",
        },
        "en": {
            "name": "Mini App Pilot",
            "headline": "One customer journey inside Telegram without building the full product first.",
            "scope": ["home screen", "catalogue or services", "one primary action", "mobile flow adaptation", "public pilot"],
            "price": "10–12M ₫ for a typical pilot",
            "timeline": "7–10 days",
            "proof": "AVE Dental, UNIQ SMART RENT, PET NIKA, TRUE SURF",
            "cta": "Scope a Mini App pilot",
        },
    },
    "ai-operator-pilot": {
        "product": "ai-operator",
        "ru": {
            "name": "AI Operator Pilot",
            "headline": "Одна AI-задача, один канал и измеримый следующий шаг.",
            "scope": ["утверждённая база знаний", "сценарий вопросов", "правила ответа", "передача человеку или в заявку", "тестовый набор диалогов"],
            "price": "8–25M ₫",
            "timeline": "ориентир 7–14 дней",
            "proof": "MAX TOUR / AVE patterns",
            "cta": "Оценить AI Operator Pilot",
        },
        "en": {
            "name": "AI Operator Pilot",
            "headline": "One AI job, one channel and a measurable next action.",
            "scope": ["approved knowledge base", "question flow", "response rules", "human or lead handoff", "test conversation set"],
            "price": "8–25M ₫",
            "timeline": "typically 7–14 days",
            "proof": "MAX TOUR / AVE patterns",
            "cta": "Scope an AI Operator pilot",
        },
    },
    "operations-core": {
        "product": "operations",
        "ru": {
            "name": "Operations Core",
            "headline": "Одна рабочая система для клиентов, заказов и статусов команды.",
            "scope": ["основные сущности и статусы", "очередь клиентов/заказов", "ответственные", "admin/back-office", "базовая аналитика"],
            "price": "15–35M ₫",
            "timeline": "ориентир 2–4 недели",
            "proof": "MAX TOUR, PET NIKA, РИЦ",
            "cta": "Разобрать Operations Core",
        },
        "en": {
            "name": "Operations Core",
            "headline": "One operating flow for customers, orders and team status.",
            "scope": ["core entities and statuses", "customer/order queue", "ownership", "admin/back office", "basic analytics"],
            "price": "15–35M ₫",
            "timeline": "typically 2–4 weeks",
            "proof": "MAX TOUR, PET NIKA, RIC",
            "cta": "Scope an Operations Core",
        },
    },
    "integration-sprint": {
        "product": "paybridge",
        "ru": {
            "name": "Integration Sprint",
            "headline": "Один надёжный мост между двумя системами — с логами, статусами и обработкой ошибок.",
            "scope": ["разбор API/webhooks", "схема событий", "одна двусторонняя или односторонняя интеграция", "логи и ошибки", "документация для передачи"],
            "price": "по техническому scope",
            "timeline": "обычно 5–10 рабочих дней после доступа к API",
            "proof": "MAX TOUR / UNIQ integration patterns",
            "cta": "Обсудить Integration Sprint",
        },
        "en": {
            "name": "Integration Sprint",
            "headline": "One reliable bridge between two systems with logs, status and error handling.",
            "scope": ["API/webhook review", "event map", "one one-way or two-way flow", "logging and errors", "handoff documentation"],
            "price": "after technical scoping",
            "timeline": "typically 5–10 working days after API access",
            "proof": "MAX TOUR / UNIQ integration patterns",
            "cta": "Discuss an Integration Sprint",
        },
    },
}

INDUSTRIES = {
    "tourism": {
        "ru": {
            "name": "Туризм",
            "headline": "Онлайн-продажи и бронирование для экскурсионных компаний и туроператоров.",
            "lead": "Клиент выбирает экскурсию, дату и параметры сам; менеджер подключается там, где действительно нужен человек.",
            "problems": ["турист уточняет цену и места в чате", "ночные обращения ждут ответа", "брони из сайта и мессенджеров расходятся", "менеджер вручную переносит данные"],
            "path": ["Каталог и подбор", "Booking", "Оплата", "CRM / back-office", "AI-консультация при необходимости"],
            "entry": "Booking Start",
            "entry_slug": "booking-start",
            "proof": ["max-tour", "rusinfocenter"],
        },
        "en": {
            "name": "Tourism",
            "headline": "Online sales and booking for tour operators and activity companies.",
            "lead": "Customers choose the tour, date and parameters themselves; staff step in where a human is actually needed.",
            "problems": ["customers ask about price and availability in chat", "after-hours enquiries wait", "bookings from web and messengers are split", "staff copy details manually"],
            "path": ["Catalogue & selection", "Booking", "Payment", "CRM / back office", "AI assistance when useful"],
            "entry": "Booking Start",
            "entry_slug": "booking-start",
            "proof": ["max-tour", "rusinfocenter"],
        },
    },
    "rental": {
        "ru": {
            "name": "Аренда",
            "headline": "Каталог, доступность, цена и заявка для проката транспорта и других rental-бизнесов.",
            "lead": "Клиент выбирает объект и даты, видит понятные условия, а команда получает структурированный запрос вместо длинной переписки.",
            "problems": ["цены считают вручную", "доступность проверяют в чате", "заявки не связаны с парком", "статусы аренды ведутся отдельно"],
            "path": ["Каталог", "Расчёт цены", "Даты / доступность", "Заявка или Booking", "Operations"],
            "entry": "Catalog + Quote",
            "entry_slug": "mini-app-pilot",
            "proof": ["uniq-smart-rent"],
        },
        "en": {
            "name": "Rental",
            "headline": "Catalogue, availability, pricing and requests for vehicle and rental businesses.",
            "lead": "Customers choose the asset and dates, see clear terms and send a structured request instead of a long chat.",
            "problems": ["pricing is calculated manually", "availability is checked in chat", "requests are disconnected from inventory", "rental status is tracked elsewhere"],
            "path": ["Catalogue", "Price calculation", "Dates / availability", "Request or Booking", "Operations"],
            "entry": "Catalog + Quote",
            "entry_slug": "mini-app-pilot",
            "proof": ["uniq-smart-rent"],
        },
    },
    "clinics": {
        "ru": {
            "name": "Клиники",
            "headline": "Запись, клиентский кабинет и повторные обращения для медицинских и ветеринарных клиник.",
            "lead": "Пациент или владелец питомца проходит понятный путь до записи, а клиника получает структурированный контекст и может автоматизировать напоминания.",
            "problems": ["лид теряется до записи", "слот согласуется вручную", "повторный визит зависит от памяти администратора", "данные клиента разнесены по системам"],
            "path": ["Услуги и специалисты", "Booking", "Профиль клиента", "Напоминания", "CRM / повторные визиты"],
            "entry": "Mini App + Booking",
            "entry_slug": "booking-start",
            "proof": ["ave-dental", "pet-nika"],
        },
        "en": {
            "name": "Clinics",
            "headline": "Booking, customer account and repeat care for medical and veterinary clinics.",
            "lead": "Patients or pet owners follow a clear path to booking while the clinic receives structured context and can automate reminders.",
            "problems": ["leads drop before booking", "slots are arranged manually", "repeat visits depend on staff memory", "customer data is spread across systems"],
            "path": ["Services & specialists", "Booking", "Customer profile", "Reminders", "CRM / repeat visits"],
            "entry": "Mini App + Booking",
            "entry_slug": "booking-start",
            "proof": ["ave-dental", "pet-nika"],
        },
    },
}

INDUSTRY_CATALOG = {
    "ru": ["Туризм", "Аренда", "Клиники", "Beauty / SPA", "Hospitality", "Restaurants", "Retail", "Real Estate", "Education", "Events", "E-commerce", "Service business", "Logistics", "Manufacturing", "Telecom"],
    "en": ["Tourism", "Rental", "Clinics", "Beauty / SPA", "Hospitality", "Restaurants", "Retail", "Real Estate", "Education", "Events", "E-commerce", "Service business", "Logistics", "Manufacturing", "Telecom"],
}

TARGET_LANDINGS = {
    "tourism/booking": {
        "industry": "tourism", "product": "booking", "offer": "booking-start",
        "ru": {
            "title": "Автоматизация бронирования экскурсий",
            "headline": "Турист бронирует экскурсию сам. Менеджер получает готовый заказ.",
            "lead": "Выбор экскурсии, даты, количества людей и дополнительных параметров переносится из переписки в один понятный сценарий бронирования.",
            "specific": ["ночные заявки не ждут открытия офиса", "менеджер меньше времени тратит на одинаковые уточнения", "структура заказа сразу готова для рабочей панели"],
        },
        "en": {
            "title": "Tour booking automation",
            "headline": "The traveller books the tour; the team receives a complete order.",
            "lead": "Tour, date, party size and options move from chat into one structured booking flow.",
            "specific": ["after-hours enquiries do not wait for the office", "staff spend less time on repetitive clarification", "the order arrives ready for back office"],
        },
    },
    "tourism/ai-operator": {
        "industry": "tourism", "product": "ai-operator", "offer": "ai-operator-pilot",
        "ru": {
            "title": "AI-консультант для турагентства",
            "headline": "AI помогает туристу выбрать экскурсию и передаёт менеджеру уже понятный запрос.",
            "lead": "Консультант работает по вашему каталогу и правилам, задаёт уточняющие вопросы и ведёт к бронированию или человеку.",
            "specific": ["ответы по каталогу 24/7", "подбор по интересам, дате и составу группы", "передача контекста в Booking или менеджеру"],
        },
        "en": {
            "title": "AI assistant for tour companies",
            "headline": "AI helps the traveller choose and hands a clear request to the team.",
            "lead": "The assistant works from your catalogue and rules, asks clarifying questions and moves the customer to booking or a human.",
            "specific": ["catalogue answers 24/7", "recommendations by interest, date and party", "context passed to Booking or staff"],
        },
    },
    "rental/booking": {
        "industry": "rental", "product": "booking", "offer": "booking-start",
        "ru": {
            "title": "Бронирование для проката",
            "headline": "Клиент выбирает транспорт и даты без ручного расчёта в мессенджере.",
            "lead": "Каталог, период аренды, тариф и заявка соединяются в один сценарий; при необходимости добавляются депозит, CRM и обслуживание парка.",
            "specific": ["меньше вопросов «сколько стоит на эти даты?»", "заявка сразу содержит модель и период", "дальше можно связать с доступностью и рабочей панелью"],
        },
        "en": {
            "title": "Booking for rental businesses",
            "headline": "Customers choose the vehicle and dates without manual quoting in chat.",
            "lead": "Catalogue, rental period, pricing and request work as one flow; deposit, CRM and fleet operations can be added later.",
            "specific": ["fewer repetitive price questions", "the request already contains model and dates", "availability and back office can connect later"],
        },
    },
    "clinics/booking": {
        "industry": "clinics", "product": "booking", "offer": "booking-start",
        "ru": {
            "title": "Онлайн-запись для клиники",
            "headline": "Пациент выбирает услугу и время, администратор получает структурированную запись.",
            "lead": "Booking можно связать с врачами, услугами, напоминаниями и клиентским кабинетом — без полной замены текущей системы клиники.",
            "specific": ["меньше ручного согласования времени", "контекст пациента приходит вместе с записью", "напоминания снижают долю забытых визитов"],
        },
        "en": {
            "title": "Online booking for clinics",
            "headline": "Patients choose the service and time; the clinic receives a structured booking.",
            "lead": "Booking can connect to doctors, services, reminders and customer accounts without replacing the clinic's entire system.",
            "specific": ["less manual slot coordination", "patient context arrives with the booking", "reminders reduce forgotten appointments"],
        },
    },
    "clinics/ai-operator": {
        "industry": "clinics", "product": "ai-operator", "offer": "ai-operator-pilot",
        "ru": {
            "title": "AI-консультант для клиники",
            "headline": "AI отвечает на типовые вопросы и помогает довести обращение до записи.",
            "lead": "Работает только по утверждённой информации о клинике и услугах, не заменяя врача и не выдавая медицинских заключений.",
            "specific": ["режим работы, услуги, подготовка и общая информация", "уточнение нужной услуги", "handoff администратору с контекстом"],
        },
        "en": {
            "title": "AI assistant for clinics",
            "headline": "AI handles routine questions and helps move the enquiry toward booking.",
            "lead": "It uses approved clinic and service information only; it does not replace a clinician or provide medical diagnosis.",
            "specific": ["hours, services, preparation and general information", "clarifies which service the customer needs", "hands context to clinic staff"],
        },
    },
    "restaurants/paybridge": {
        "industry": None, "product": "paybridge", "offer": "integration-sprint",
        "ru": {
            "title": "Payment middleware для ресторанов и POS",
            "headline": "Свяжите checkout и подтверждённый статус оплаты без ручной сверки.",
            "lead": "PayBridge подходит POS-вендорам, интеграторам и сетям, которым нужно надёжно связать кассовый сценарий с платёжным провайдером.",
            "specific": ["статус оплаты возвращается в кассовый сценарий", "webhook-события обрабатываются системно", "есть основа для reconciliation и rollout на сеть"],
        },
        "en": {
            "title": "Payment middleware for restaurants and POS",
            "headline": "Connect checkout and verified payment status without manual reconciliation.",
            "lead": "PayBridge is for POS vendors, integrators and chains that need a controlled payment flow between checkout and provider.",
            "specific": ["payment status returns to the checkout flow", "webhook events are handled systematically", "ready for reconciliation and multi-location rollout"],
        },
    },
}


MODULES = {
    "online-booking": {
        "product": "booking",
        "ru": {
            "name": "Онлайн-бронирование",
            "short": "Клиент сам выбирает услугу, дату и параметры. Вы получаете готовую бронь.",
            "result": "Убирает ручное согласование дат и одинаковые вопросы в мессенджере.",
            "price": "8–18M ₫",
            "timeline": "обычно 7–14 дней",
            "for": ["туризм", "отели", "аренда", "клиники", "услуги"],
            "steps": ["Клиент выбирает услугу", "видит доступную дату или слот", "указывает нужные параметры", "получает подтверждение", "бронь приходит команде в понятном виде"],
            "includes": ["один законченный сценарий бронирования", "даты / слоты", "основные параметры", "подтверждение", "адаптация под телефон"],
            "excludes": ["полная замена вашей CRM", "сложные сторонние интеграции без отдельной оценки", "миграция всей базы данных"],
            "proof": ["max-tour", "ave-dental", "pet-nika", "true-surf"],
            "cta": "Оценить онлайн-бронирование",
        },
        "en": {
            "name": "Online booking",
            "short": "Customers choose the service, date and parameters; your team receives a complete booking.",
            "result": "Removes manual date coordination and repetitive booking questions.",
            "price": "US$330–740",
            "timeline": "typically 7–14 days",
            "for": ["tourism", "hotels", "rental", "clinics", "services"],
            "steps": ["Customer selects a service", "sees available dates or slots", "enters the required details", "receives confirmation", "the team receives a structured booking"],
            "includes": ["one complete booking flow", "dates / slots", "core parameters", "confirmation", "mobile adaptation"],
            "excludes": ["full CRM replacement", "complex third-party integrations without separate scoping", "full database migration"],
            "proof": ["max-tour", "ave-dental", "pet-nika", "true-surf"],
            "cta": "Scope online booking",
        },
    },
    "telegram-mini-app": {
        "product": "online-sales",
        "ru": {
            "name": "Telegram Mini App",
            "short": "Каталог, услуги, запись или заявка открываются прямо внутри Telegram.",
            "result": "Клиенту не нужно переходить по нескольким сайтам и собирать информацию в переписке.",
            "price": "10–12M ₫ за типовой первый запуск",
            "timeline": "обычно 7–10 дней",
            "for": ["туризм", "аренда", "клиники", "магазины", "услуги"],
            "steps": ["Клиент открывает Mini App", "видит услуги или каталог", "выбирает нужное", "оставляет заявку или бронирует", "данные передаются вам"],
            "includes": ["главный экран", "каталог или услуги", "одно ключевое действие", "мобильный интерфейс", "публичная рабочая версия"],
            "excludes": ["большая CRM", "сложная ERP", "неограниченное число нестандартных интеграций"],
            "proof": ["uniq-smart-rent", "ave-dental", "pet-nika", "true-surf"],
            "cta": "Оценить Mini App",
        },
        "en": {
            "name": "Telegram Mini App",
            "short": "Catalogue, services, booking or enquiry flow directly inside Telegram.",
            "result": "Customers do not need to jump between websites and chats to complete one action.",
            "price": "US$410–495 for a typical first release",
            "timeline": "typically 7–10 days",
            "for": ["tourism", "rental", "clinics", "retail", "services"],
            "steps": ["Customer opens the Mini App", "sees services or catalogue", "chooses an option", "books or sends an enquiry", "the data reaches your team"],
            "includes": ["home screen", "catalogue or services", "one primary action", "mobile UI", "public working release"],
            "excludes": ["large CRM", "complex ERP", "unlimited custom integrations"],
            "proof": ["uniq-smart-rent", "ave-dental", "pet-nika", "true-surf"],
            "cta": "Scope a Mini App",
        },
    },
    "crm": {
        "product": "operations",
        "ru": {
            "name": "CRM для заявок и заказов",
            "short": "Все обращения, заказы, статусы и ответственные — в одной рабочей панели.",
            "result": "Сотрудники перестают искать информацию по чатам и таблицам, а руководитель видит, что происходит.",
            "price": "15–35M ₫ за первый рабочий раздел",
            "timeline": "обычно 2–4 недели",
            "for": ["туризм", "отели", "аренда", "клиники", "магазины", "услуги"],
            "steps": ["Заявка попадает в систему", "получает статус и ответственного", "сотрудник видит следующий шаг", "история сохраняется", "руководитель видит очередь и показатели"],
            "includes": ["клиенты и заказы", "статусы", "ответственные", "рабочая панель", "базовая аналитика"],
            "excludes": ["замена всех корпоративных систем сразу", "миграция сложной legacy-базы без отдельного этапа", "неограниченные отчёты"],
            "proof": ["max-tour", "pet-nika", "rusinfocenter"],
            "cta": "Разобрать CRM под мой процесс",
        },
        "en": {
            "name": "CRM for leads and orders",
            "short": "Enquiries, orders, status and ownership in one working interface.",
            "result": "Staff stop searching across chats and spreadsheets, while management gets a clear operating view.",
            "price": "US$620–1,450 for the first working area",
            "timeline": "typically 2–4 weeks",
            "for": ["tourism", "hotels", "rental", "clinics", "retail", "services"],
            "steps": ["A lead enters the system", "gets a status and owner", "staff see the next action", "history is preserved", "management sees the queue and key numbers"],
            "includes": ["customers and orders", "statuses", "ownership", "working interface", "basic analytics"],
            "excludes": ["replacing every corporate system at once", "complex legacy migration without a separate phase", "unlimited custom reporting"],
            "proof": ["max-tour", "pet-nika", "rusinfocenter"],
            "cta": "Map CRM for my workflow",
        },
    },
    "ai-consultant": {
        "product": "ai-operator",
        "ru": {
            "name": "AI-консультант",
            "short": "Отвечает по вашим услугам, уточняет запрос и передаёт менеджеру уже понятную заявку.",
            "result": "Снимает повторяющиеся вопросы и помогает клиенту выбрать без ожидания ответа сотрудника.",
            "price": "8–25M ₫",
            "timeline": "обычно 7–14 дней",
            "for": ["туризм", "отели", "клиники", "магазины", "услуги"],
            "steps": ["Клиент задаёт вопрос", "AI отвечает только по утверждённой информации", "уточняет параметры", "предлагает подходящий вариант", "передаёт менеджеру контекст или ведёт к записи"],
            "includes": ["одна задача", "один канал", "утверждённая база знаний", "правила ответа", "передача человеку"],
            "excludes": ["свободные ответы вне согласованной базы", "медицинские заключения", "неограниченные действия без подтверждения"],
            "proof": ["max-tour"],
            "cta": "Показать AI на моём сценарии",
        },
        "en": {
            "name": "AI assistant",
            "short": "Answers from your approved information, clarifies the request and passes a useful lead to staff.",
            "result": "Handles repetitive questions and helps customers choose without waiting for staff.",
            "price": "US$330–1,030",
            "timeline": "typically 7–14 days",
            "for": ["tourism", "hotels", "clinics", "retail", "services"],
            "steps": ["Customer asks a question", "AI answers from approved information only", "clarifies the request", "suggests a relevant option", "passes context to staff or moves to booking"],
            "includes": ["one defined task", "one channel", "approved knowledge base", "response rules", "human handoff"],
            "excludes": ["free-form answers outside the approved base", "medical diagnosis", "unlimited actions without confirmation"],
            "proof": ["max-tour"],
            "cta": "See AI on my scenario",
        },
    },
    "payment-integration": {
        "product": "paybridge",
        "ru": {
            "name": "Подключение оплаты",
            "short": "Оплата на сайте, в приложении или кассе связывается с заказом и возвращает подтверждённый статус.",
            "result": "Не нужно вручную проверять, оплатил ли клиент и к какому заказу относится платёж.",
            "price": "10–30M ₫ для типовой интеграции",
            "timeline": "после проверки API платёжного провайдера",
            "for": ["туризм", "отели", "магазины", "рестораны", "аренда"],
            "steps": ["Клиент оплачивает", "провайдер подтверждает платёж", "система проверяет событие", "заказ получает статус", "данные передаются в рабочую панель"],
            "includes": ["один платёжный сценарий", "обработка статуса", "ошибки и повторные события", "логи", "документация"],
            "excludes": ["комиссии платёжного провайдера", "сертификация чужого POS", "несколько провайдеров без отдельной оценки"],
            "proof": ["max-tour"],
            "cta": "Обсудить подключение оплаты",
        },
        "en": {
            "name": "Payment integration",
            "short": "Connect payment on website, app or POS to the order and return verified status.",
            "result": "Removes manual payment checking and connects the transaction to the right order.",
            "price": "US$410–1,240 for a typical integration",
            "timeline": "after reviewing the payment provider API",
            "for": ["tourism", "hotels", "retail", "restaurants", "rental"],
            "steps": ["Customer pays", "provider confirms payment", "the event is validated", "the order status updates", "data reaches the working system"],
            "includes": ["one payment flow", "status handling", "errors and repeat events", "logging", "handoff documentation"],
            "excludes": ["provider fees", "third-party POS certification", "multiple providers without separate scoping"],
            "proof": ["max-tour"],
            "cta": "Discuss payment integration",
        },
    },
    "catalog": {
        "product": "online-sales",
        "ru": {
            "name": "Каталог с ценами",
            "short": "Клиент видит товары или услуги, варианты и стоимость до разговора с менеджером.",
            "result": "Сокращает вопросы «что есть?» и «сколько стоит?» и приводит к более готовой заявке.",
            "price": "от 5M ₫",
            "timeline": "обычно 5–10 дней",
            "for": ["туризм", "магазины", "аренда", "услуги"],
            "steps": ["Показываем категории", "карточки товара или услуги", "варианты и цену", "клиент выбирает", "переходит к заявке или бронированию"],
            "includes": ["структура каталога", "карточки", "цены", "фильтры базового уровня", "одно целевое действие"],
            "excludes": ["полноценная ERP", "сложный складской учёт", "маркетплейс с множеством продавцов"],
            "proof": ["uniq-smart-rent", "max-tour"],
            "cta": "Оценить каталог",
        },
        "en": {
            "name": "Catalogue with pricing",
            "short": "Customers see products or services, options and price before speaking to staff.",
            "result": "Reduces repetitive availability and pricing questions and produces better-qualified enquiries.",
            "price": "from US$205",
            "timeline": "typically 5–10 days",
            "for": ["tourism", "retail", "rental", "services"],
            "steps": ["Show categories", "product or service cards", "options and price", "customer chooses", "moves to enquiry or booking"],
            "includes": ["catalogue structure", "cards", "pricing", "basic filters", "one primary action"],
            "excludes": ["full ERP", "complex inventory management", "multi-vendor marketplace"],
            "proof": ["uniq-smart-rent", "max-tour"],
            "cta": "Scope a catalogue",
        },
    },
    "customer-account": {
        "product": "online-sales",
        "ru": {
            "name": "Личный кабинет клиента",
            "short": "Клиент видит свои записи, заказы, статусы и повторные действия в одном месте.",
            "result": "Снижает количество вопросов о статусе и упрощает повторные обращения.",
            "price": "после короткого разбора",
            "timeline": "обычно от 2 недель",
            "for": ["отели", "аренда", "клиники", "услуги"],
            "steps": ["Клиент входит", "видит свои данные", "проверяет статус", "повторяет нужное действие", "обновления сохраняются в системе"],
            "includes": ["профиль", "история", "статусы", "основные действия", "мобильная версия"],
            "excludes": ["полная CRM", "сложная программа лояльности", "нестандартная авторизация без отдельной оценки"],
            "proof": ["pet-nika", "true-surf"],
            "cta": "Обсудить личный кабинет",
        },
        "en": {
            "name": "Customer account",
            "short": "Customers see bookings, orders, status and repeat actions in one place.",
            "result": "Reduces status questions and makes repeat interactions easier.",
            "price": "after a short review",
            "timeline": "typically from 2 weeks",
            "for": ["hotels", "rental", "clinics", "services"],
            "steps": ["Customer signs in", "sees their data", "checks status", "repeats an action", "updates are stored in the system"],
            "includes": ["profile", "history", "statuses", "core actions", "mobile version"],
            "excludes": ["full CRM", "complex loyalty programme", "custom authentication without separate scoping"],
            "proof": ["pet-nika", "true-surf"],
            "cta": "Discuss a customer account",
        },
    },
    "internal-dashboard": {
        "product": "operations",
        "ru": {
            "name": "Рабочая панель для сотрудников",
            "short": "Заказы, статусы, расписание и действия команды собраны в одном интерфейсе.",
            "result": "Убирает ручные переносы между чатами и таблицами.",
            "price": "от 15M ₫",
            "timeline": "обычно 2–4 недели",
            "for": ["туризм", "отели", "аренда", "клиники", "рестораны"],
            "steps": ["Сотрудник видит очередь", "открывает заказ", "меняет статус", "выполняет следующее действие", "руководитель видит общую картину"],
            "includes": ["очередь", "статусы", "роли", "основные действия", "базовая аналитика"],
            "excludes": ["вся ERP", "полная бухгалтерия", "неограниченный набор ролей без оценки"],
            "proof": ["max-tour", "pet-nika"],
            "cta": "Разобрать рабочую панель",
        },
        "en": {
            "name": "Staff dashboard",
            "short": "Orders, status, schedule and team actions in one working interface.",
            "result": "Removes manual copying between chats and spreadsheets.",
            "price": "from US$620",
            "timeline": "typically 2–4 weeks",
            "for": ["tourism", "hotels", "rental", "clinics", "restaurants"],
            "steps": ["Staff see the queue", "open an order", "change status", "take the next action", "management sees the overall picture"],
            "includes": ["queue", "statuses", "roles", "core actions", "basic analytics"],
            "excludes": ["full ERP", "full accounting", "unlimited custom roles without scoping"],
            "proof": ["max-tour", "pet-nika"],
            "cta": "Scope a staff dashboard",
        },
    },
    "api-integration": {
        "product": "paybridge",
        "ru": {
            "name": "Интеграция двух систем",
            "short": "Передаём нужные данные между сайтом, CRM, кассой, оплатой или внутренней системой.",
            "result": "Сотрудникам не приходится вручную копировать данные из одной системы в другую.",
            "price": "по технической оценке",
            "timeline": "обычно 5–10 рабочих дней после доступа к API",
            "for": ["магазины", "отели", "рестораны", "корпоративные системы"],
            "steps": ["Проверяем API", "фиксируем какие данные передаются", "собираем интеграцию", "добавляем логи и обработку ошибок", "тестируем на согласованном сценарии"],
            "includes": ["одна интеграция", "карта данных", "логи", "обработка ошибок", "документация"],
            "excludes": ["недокументированные системы без доступа", "массовая миграция данных", "несколько независимых интеграций по цене одной"],
            "proof": ["max-tour", "uniq-smart-rent"],
            "cta": "Обсудить интеграцию",
        },
        "en": {
            "name": "System integration",
            "short": "Move the required data between website, CRM, POS, payments or internal systems.",
            "result": "Staff no longer need to copy data manually between systems.",
            "price": "after technical review",
            "timeline": "typically 5–10 working days after API access",
            "for": ["retail", "hotels", "restaurants", "enterprise systems"],
            "steps": ["Review the API", "define the data exchange", "build the integration", "add logging and error handling", "test the agreed scenario"],
            "includes": ["one integration", "data map", "logging", "error handling", "documentation"],
            "excludes": ["undocumented systems without access", "mass data migration", "multiple unrelated integrations for one fixed price"],
            "proof": ["max-tour", "uniq-smart-rent"],
            "cta": "Discuss an integration",
        },
    },
}

INDUSTRY_EXPLORER = {
    "tourism": {"ru": {"name": "Туризм", "lead": "Экскурсии, туры, трансферы и активности."}, "en": {"name": "Tourism", "lead": "Tours, transfers and activities."}, "modules": ["online-booking", "catalog", "telegram-mini-app", "ai-consultant", "crm", "payment-integration"]},
    "hotels": {"ru": {"name": "Отели", "lead": "Прямое бронирование, работа с гостем и дополнительные услуги."}, "en": {"name": "Hotels", "lead": "Direct booking, guest service and add-ons."}, "modules": ["online-booking", "customer-account", "ai-consultant", "crm", "payment-integration"]},
    "shops": {"ru": {"name": "Магазины", "lead": "Каталог, заявки, повторные продажи и оплата."}, "en": {"name": "Retail", "lead": "Catalogue, enquiries, repeat sales and payments."}, "modules": ["catalog", "crm", "ai-consultant", "payment-integration", "api-integration"]},
    "rental": {"ru": {"name": "Аренда", "lead": "Транспорт, оборудование и другие объекты аренды."}, "en": {"name": "Rental", "lead": "Vehicles, equipment and other rental assets."}, "modules": ["catalog", "online-booking", "crm", "payment-integration", "customer-account"]},
    "clinics": {"ru": {"name": "Клиники", "lead": "Запись, кабинет клиента, напоминания и типовые вопросы."}, "en": {"name": "Clinics", "lead": "Booking, customer account, reminders and routine questions."}, "modules": ["online-booking", "telegram-mini-app", "customer-account", "crm", "ai-consultant"]},
    "restaurants": {"ru": {"name": "Рестораны", "lead": "Бронь, заказ, оплата и работа персонала."}, "en": {"name": "Restaurants", "lead": "Reservations, orders, payments and staff workflow."}, "modules": ["online-booking", "payment-integration", "internal-dashboard", "api-integration"]},
    "services": {"ru": {"name": "Услуги", "lead": "Запись, заявки, консультации и повторные обращения."}, "en": {"name": "Services", "lead": "Booking, enquiries, consultation and repeat business."}, "modules": ["telegram-mini-app", "online-booking", "crm", "ai-consultant", "payment-integration"]},
    "enterprise": {"ru": {"name": "Крупные системы", "lead": "Интеграции, данные и закрытые внутренние процессы."}, "en": {"name": "Enterprise", "lead": "Integrations, data and private internal workflows."}, "modules": ["api-integration", "internal-dashboard", "crm", "payment-integration"]},
}

CASES = {
    "max-tour": {
        "ru": {"name": "MAX TOUR", "industry": "Туризм", "status": "working-demo", "status_label": "ИНТЕРАКТИВНОЕ ДЕМО", "summary": "Клиентский путь, бронирование, роли, рабочая панель и аналитика для экскурсионного бизнеса.", "shows": ["Booking", "Operations", "AI"], "demo": "https://max-tour.viiversion.com/"},
        "en": {"name": "MAX TOUR", "industry": "Tourism", "status": "working-demo", "status_label": "WORKING DEMO", "summary": "Customer flow, booking, roles, admin and owner analytics for a tour business.", "shows": ["Booking", "Operations", "AI"], "demo": "https://max-tour.viiversion.com/"},
    },
    "uniq-smart-rent": {
        "ru": {"name": "UNIQ SMART RENT", "industry": "Аренда", "status": "working-demo", "status_label": "ИНТЕРАКТИВНОЕ ДЕМО", "summary": "Каталог, цены и путь заявки для аренды транспорта.", "shows": ["Online Sales", "Booking", "Operations"], "demo": "https://uniq-smart-rent.mirozdanie6v.workers.dev/"},
        "en": {"name": "UNIQ SMART RENT", "industry": "Rental", "status": "working-demo", "status_label": "WORKING DEMO", "summary": "Catalogue, pricing and request lifecycle for vehicle rental.", "shows": ["Online Sales", "Booking", "Operations"], "demo": "https://uniq-smart-rent.mirozdanie6v.workers.dev/"},
    },
    "pet-nika": {
        "ru": {"name": "PET NIKA", "industry": "Veterinary", "status": "prototype", "status_label": "ПУБЛИЧНЫЙ ПРОТОТИП", "summary": "Клиентский кабинет, питомцы, обращения, запись и рабочая панель.", "shows": ["Online Sales", "Booking", "Operations"], "demo": "https://pet-nika.viiversion.com/"},
        "en": {"name": "PET NIKA", "industry": "Veterinary", "status": "prototype", "status_label": "PUBLIC PROTOTYPE", "summary": "Customer account, pets, requests, booking and admin layer.", "shows": ["Online Sales", "Booking", "Operations"], "demo": "https://pet-nika.viiversion.com/"},
    },
    "ave-dental": {
        "ru": {"name": "AVE Dental", "industry": "Dental", "status": "prototype", "status_label": "ПУБЛИЧНЫЙ ПРОТОТИП", "summary": "Мультиязычный Mini App и сценарий онлайн-записи для клиники.", "shows": ["Online Sales", "Booking"], "demo": "https://ave-dental-miniapp.vercel.app/"},
        "en": {"name": "AVE Dental", "industry": "Dental", "status": "prototype", "status_label": "PUBLIC PROTOTYPE", "summary": "Multilingual Mini App and booking flow for a clinic.", "shows": ["Online Sales", "Booking"], "demo": "https://ave-dental-miniapp.vercel.app/"},
    },
    "rusinfocenter": {
        "ru": {"name": "Русский Информационный Центр", "industry": "Туризм", "status": "concept", "status_label": "КЛИЕНТСКАЯ КОНЦЕПЦИЯ", "summary": "Цифровой клиентский путь и архитектура будущей системы продаж.", "shows": ["Online Sales", "Booking", "Integrations"], "demo": "https://rusinfocenter.viiversion.com/"},
        "en": {"name": "Russian Information Center", "industry": "Tourism", "status": "concept", "status_label": "CLIENT CONCEPT", "summary": "Customer journey and architecture for a future sales system.", "shows": ["Online Sales", "Booking", "Integrations"], "demo": "https://rusinfocenter.viiversion.com/"},
    },
    "g-beauty": {
        "ru": {"name": "G-Beauty", "industry": "Beauty", "status": "prototype", "status_label": "ПУБЛИЧНЫЙ ПРОТОТИП", "summary": "Лендинг, Mini App, онлайн-запись и демонстрационная рабочая панель для beauty-бизнеса.", "shows": ["Online Sales", "Booking", "Operations"], "demo": "https://gbeauty-vien-trieu-prototype.mirozdanie6v.workers.dev/"},
        "en": {"name": "G-Beauty", "industry": "Beauty", "status": "prototype", "status_label": "PUBLIC PROTOTYPE", "summary": "Landing, Mini App, booking and demo admin for a local beauty business.", "shows": ["Online Sales", "Booking", "Operations"], "demo": "https://gbeauty-vien-trieu-prototype.mirozdanie6v.workers.dev/"},
    },
    "true-surf": {
        "ru": {"name": "TRUE SURF", "industry": "Activities", "status": "prototype", "status_label": "ПУБЛИЧНЫЙ ПРОТОТИП", "summary": "Онлайн-запись, профиль клиента и повторные действия в формате Mini App.", "shows": ["Online Sales", "Booking"], "demo": "https://truesurf-app.viiversion.com/"},
        "en": {"name": "TRUE SURF", "industry": "Activities", "status": "prototype", "status_label": "PUBLIC PROTOTYPE", "summary": "Booking, client passport and repeat flow in a Mini App.", "shows": ["Online Sales", "Booking"], "demo": "https://truesurf-app.viiversion.com/"},
    },
}

LABS = {
    "proposal-studio": {
        "ru": {"name": "Proposal Studio", "status": "ДОСТУПНО", "summary": "Исследование → диагностика → решение → коммерческое предложение → проверка.", "url": "/proposal-studio/"},
        "en": {"name": "Proposal Studio", "status": "AVAILABLE", "summary": "Исследование → диагностика → решение → коммерческое предложение → проверка.", "url": "/proposal-studio/"},
    },
    "mini-app-factory": {
        "ru": {"name": "Mini App Factory", "status": "ЗАКРЫТАЯ БЕТА", "summary": "Платформа для серийной сборки клиентских Mini Apps под брендом партнёра.", "url": None},
        "en": {"name": "Mini App Factory", "status": "PRIVATE BETA", "summary": "A white-label production line for repeatable client Mini App delivery.", "url": None},
    },
    "zl-web-agent": {
        "ru": {"name": "ZL Web Agent", "status": "ЗАКРЫТАЯ БЕТА", "summary": "Аудит WordPress на основе фактических данных и план безопасных изменений.", "url": None},
        "en": {"name": "ZL Web Agent", "status": "PRIVATE BETA", "summary": "Evidence-based WordPress audit and a safe change plan.", "url": None},
    },
    "video-human-editor": {
        "ru": {"name": "Event Video Human Editor", "status": "В РАЗРАБОТКЕ", "summary": "Семантический анализ больших массивов видео до ручного монтажа.", "url": None},
        "en": {"name": "Event Video Human Editor", "status": "IN DEVELOPMENT", "summary": "Semantic analysis of large event-video collections before human editing.", "url": None},
    },
}

TEAM = {
    "ru": [
        ("Дмитрий Владимиров", "Серверная архитектура и данные · базы данных · интеграции", "20+ лет в IT и telecom. Отвечает за серверную логику, данные, интеграции, надёжность и техническую архитектуру."),
        ("Ольга Ногтич", "Продуктовая архитектура · интерфейсы · AI-автоматизация", "16+ лет в digital и визуальных коммуникациях. Отвечает за логику продукта, пользовательские сценарии, интерфейсы, исследования и AI-автоматизацию."),
    ],
    "en": [
        ("Dmitrii Vladimirov", "Systems architecture · databases · integrations · development", "Oracle, PL/SQL, ETL, Linux, API, telecom BSS / Revenue Assurance. Experience with complex telecom and international systems."),
        ("Olga Nogtich", "Product · UX/UI · research · content", "Product logic, interfaces, customer journeys, research and visual communication."),
    ],
}

NAV = {
    "ru": [("Отрасли", "/#industries"), ("Что можно купить", "/modules/"), ("Примеры", "/cases/"), ("Для крупных систем", "/enterprise/"), ("О нас", "/about/")],
    "en": [("Solutions", "/solutions/"), ("Products", "/products/"), ("Cases", "/cases/"), ("Enterprise", "/enterprise/"), ("Company", "/about/")],
}
