# Client-facing content for the VIIVERSION product site.
# Keep marketing copy here; templates and rendering belong in build-product-site.py.

LANGS = ("ru", "en")

BRAND = {
    "ru": {
        "tagline": "Цифровые системы для продаж и операций",
        "hero_title": "Автоматизируем продажи и операции — от одного процесса до единой системы.",
        "hero_lead": "Бронирование, клиентские приложения, CRM, AI, платежи и интеграции. Можно внедрить один модуль или связать несколько — без полной замены того, что уже работает.",
        "hero_primary": "Найти решение для задачи",
        "hero_secondary": "Посмотреть рабочие демо",
        "problem_title": "Что сейчас тормозит процесс?",
        "problem_lead": "Начинаем не с набора технологий, а с одного участка, где теряется время, заявки или данные.",
        "products_title": "Основные продукты",
        "products_lead": "Каждый продукт решает самостоятельную задачу и при необходимости соединяется с другими.",
        "proof_title": "Рабочие демо и прототипы",
        "proof_lead": "Показываем не только интерфейс, но и сценарий: что делает клиент, что получает команда и какие части уже реализованы.",
        "start_title": "Начните с одной небольшой задачи",
        "start_lead": "Фиксированный первый шаг проще согласовать и проверить. Если он даёт результат, расширяем систему дальше.",
        "matrix_title": "Один продукт — разные сценарии для разных отраслей",
        "matrix_lead": "Выберите продукт и посмотрите, где он применим. Сама технология остаётся знакомой, а сценарий меняется под процесс бизнеса.",
        "special_title": "Для партнёров и сложных внутренних систем",
        "team_title": "Инженерия и продуктовый дизайн в одной команде",
        "final_title": "Покажите один процесс, который хотите улучшить.",
        "final_lead": "Мы разберём текущий путь, предложим минимальный рабочий вариант и сразу скажем, что действительно имеет смысл делать первым.",
    },
    "en": {
        "tagline": "Digital systems for sales and operations",
        "hero_title": "Automate sales and operations — from one process to a connected system.",
        "hero_lead": "Booking, customer apps, CRM, AI, payments and integrations. Start with one module or connect several without replacing everything that already works.",
        "hero_primary": "Find a solution for my problem",
        "hero_secondary": "See working demos",
        "problem_title": "Where is the process breaking today?",
        "problem_lead": "We start with one point where time, leads or data are being lost — not with a shopping list of technologies.",
        "products_title": "Core products",
        "products_lead": "Each product solves a useful problem on its own and can connect to the rest when needed.",
        "proof_title": "Working demos and prototypes",
        "proof_lead": "We show the customer flow, team workflow and what is already implemented — not just interface screenshots.",
        "start_title": "Start with one small, testable task",
        "start_lead": "A fixed first step is easier to approve and verify. If it works, the system can grow from there.",
        "matrix_title": "One product, different industry scenarios",
        "matrix_lead": "Choose a product and see where it fits. The core technology stays familiar while the workflow changes around the business.",
        "special_title": "For partners and complex internal systems",
        "team_title": "Engineering and product design in one team",
        "final_title": "Show us one process you want to improve.",
        "final_lead": "We will map the current flow, propose the smallest useful change and tell you what is worth building first.",
    },
}

PRODUCTS = {
    "online-sales": {
        "ru": {
            "name": "Online Sales",
            "label": "Клиентский путь",
            "headline": "Сайт, Mini App или каталог, который ведёт клиента к понятному действию.",
            "summary": "Показываем предложение, помогаем выбрать, собираем нужные параметры и передаём заявку или заказ дальше без лишней переписки.",
            "before": ["клиент ищет цену в переписке", "заявки приходят из разных каналов", "менеджер вручную уточняет одни и те же данные"],
            "after": ["клиент видит предложение и условия", "система собирает нужные параметры", "заявка сразу приходит в понятном формате"],
            "modules": [
                ("Landing / сайт", "Один понятный путь от оффера до действия."),
                ("Telegram Mini App", "Каталог, услуги, профиль или заявка внутри Telegram."),
                ("Zalo Mini App", "Локальный клиентский сценарий для рынка Вьетнама."),
                ("Каталог и цены", "Клиент видит варианты и стоимость до разговора с менеджером."),
                ("Клиентский кабинет", "История, статусы и повторные действия в одном месте."),
            ],
            "price": "от 2.5M ₫ за landing; Mini App — 10–12M ₫ за типовой первый запуск",
            "timeline": "от 7–10 дней для типового Mini App",
            "offer": "mini-app-pilot",
            "proof": ["uniq-smart-rent", "ave-dental", "g-beauty", "true-surf"],
            "cta": "Получить оценку клиентского сценария",
        },
        "en": {
            "name": "Online Sales",
            "label": "Customer journey",
            "headline": "A website, Mini App or catalogue that moves the customer to a clear next action.",
            "summary": "Present the offer, help the customer choose, collect the right parameters and hand a structured lead or order to the team.",
            "before": ["customers ask for prices in chat", "leads arrive through disconnected channels", "staff repeatedly collect the same details"],
            "after": ["customers see the offer and terms", "the system collects the required inputs", "the team receives a structured lead"],
            "modules": [
                ("Landing / website", "One clear path from offer to action."),
                ("Telegram Mini App", "Catalogue, services, profile or order flow inside Telegram."),
                ("Zalo Mini App", "A local customer flow for the Vietnam market."),
                ("Catalogue & pricing", "Customers see options and pricing before talking to staff."),
                ("Customer account", "History, status and repeat actions in one place."),
            ],
            "price": "from 2.5M ₫ for a landing; typical Mini App pilot 10–12M ₫",
            "timeline": "from 7–10 days for a typical Mini App pilot",
            "offer": "mini-app-pilot",
            "proof": ["uniq-smart-rent", "ave-dental", "g-beauty", "true-surf"],
            "cta": "Get a scope for my customer flow",
        },
    },
    "booking": {
        "ru": {
            "name": "Booking",
            "label": "Бронирование и расписание",
            "headline": "Бронирование без длинной переписки с менеджером.",
            "summary": "Клиент выбирает услугу, дату и параметры сам. Команда получает полный заказ, а не цепочку сообщений, которую ещё нужно собирать вручную.",
            "before": ["клиент спрашивает о свободной дате", "менеджер проверяет таблицу или чат", "цена и параметры уточняются в нескольких сообщениях", "бронь переносится вручную"],
            "after": ["клиент выбирает дату и параметры", "система рассчитывает или показывает условия", "бронь создаётся в структурированном виде", "команда получает готовый заказ"],
            "modules": [
                ("Booking Engine", "Собирает услугу, дату, количество и дополнительные параметры."),
                ("Расписание", "Показывает доступные даты и слоты."),
                ("Каталог и цены", "Связывает бронирование с услугой и тарифом."),
                ("Подтверждения", "Отправляет клиенту и команде статус брони."),
                ("Напоминания", "Автоматически напоминает о предстоящей услуге."),
            ],
            "price": "8–18M ₫ за базовый Booking Start",
            "timeline": "ориентир 7–14 дней для одного законченного сценария",
            "offer": "booking-start",
            "proof": ["max-tour", "ave-dental", "pet-nika", "true-surf"],
            "cta": "Получить оценку Booking для моего процесса",
        },
        "en": {
            "name": "Booking",
            "label": "Booking & scheduling",
            "headline": "Booking without a long back-and-forth with staff.",
            "summary": "The customer chooses the service, date and parameters. The team receives a complete structured booking instead of reconstructing it from messages.",
            "before": ["the customer asks about availability", "staff check a spreadsheet or chat", "price and details are clarified over several messages", "the booking is copied manually"],
            "after": ["the customer selects date and parameters", "the system shows price or terms", "a structured booking is created", "the team receives a complete order"],
            "modules": [
                ("Booking Engine", "Collects service, date, quantity and options."),
                ("Schedule", "Shows available dates and slots."),
                ("Catalogue & pricing", "Connects the booking to a service and tariff."),
                ("Confirmations", "Sends booking status to customer and team."),
                ("Reminders", "Automatically reminds the customer before the service."),
            ],
            "price": "8–18M ₫ for a basic Booking Start",
            "timeline": "typically 7–14 days for one complete booking flow",
            "offer": "booking-start",
            "proof": ["max-tour", "ave-dental", "pet-nika", "true-surf"],
            "cta": "Get a Booking scope for my process",
        },
    },
    "operations": {
        "ru": {
            "name": "Operations",
            "label": "CRM и рабочая панель",
            "headline": "Клиенты, заказы и работа команды — в одной системе.",
            "summary": "CRM, рабочая панель, статусы и аналитика собираются вокруг реального процесса бизнеса — без переноса данных между отдельными таблицами и чатами.",
            "before": ["лиды и заказы разбросаны по чатам", "сотрудники держат следующий шаг в голове", "статусы обновляются вручную", "руководитель не видит общую картину"],
            "after": ["единая очередь клиентов и заказов", "понятные статусы и ответственные", "операции ведутся из одной панели", "руководитель видит ключевые показатели"],
            "modules": [
                ("CRM", "Лиды, история, статус и следующий шаг."),
                ("Back-office", "Заказы, расписание, каталог и рабочие действия команды."),
                ("Owner Dashboard", "Ключевые показатели и очередь для руководителя."),
                ("Analytics", "Источники, конверсия, загрузка и SLA."),
                ("Repeat Sales", "Напоминания и возврат клиентов по истории."),
            ],
            "price": "15–35M ₫ за CRM Core или Back-office Core",
            "timeline": "ориентир 2–4 недели для первого рабочего контура",
            "offer": "operations-core",
            "proof": ["max-tour", "pet-nika", "rusinfocenter"],
            "cta": "Разобрать текущий процесс",
        },
        "en": {
            "name": "Operations",
            "label": "CRM & back office",
            "headline": "Customers, orders and team work in one operating flow.",
            "summary": "CRM, back office, status and analytics are organised around how the business actually works instead of another isolated spreadsheet.",
            "before": ["leads and orders are scattered across chats", "staff keep the next step in their heads", "statuses are updated manually", "management lacks a single view"],
            "after": ["one queue for customers and orders", "clear status and ownership", "operations run from one workspace", "management sees the key numbers"],
            "modules": [
                ("CRM", "Lead history, status and next action."),
                ("Back office", "Orders, schedule, catalogue and team actions."),
                ("Owner Dashboard", "Key indicators and management queue."),
                ("Analytics", "Sources, conversion, load and SLA."),
                ("Repeat Sales", "Reminders and reactivation based on customer history."),
            ],
            "price": "15–35M ₫ for CRM Core or Back-office Core",
            "timeline": "typically 2–4 weeks for the first working operating flow",
            "offer": "operations-core",
            "proof": ["max-tour", "pet-nika", "rusinfocenter"],
            "cta": "Map my current workflow",
        },
    },
    "ai-operator": {
        "ru": {
            "name": "AI Operator",
            "label": "AI для продаж и поддержки",
            "headline": "AI-консультант, который знает ваш продукт и ведёт клиента к следующему действию.",
            "summary": "Отвечает только в согласованном контуре, уточняет запрос, подбирает подходящий вариант и передаёт контекст в заявку, бронирование или CRM.",
            "before": ["менеджеры отвечают на повторяющиеся вопросы", "клиенту трудно выбрать из большого каталога", "ночные обращения ждут утра", "контекст теряется при передаче человеку"],
            "after": ["AI отвечает по утверждённой базе знаний", "уточняет параметры и помогает выбрать", "передаёт структурированный контекст", "сложные запросы уходят человеку"],
            "modules": [
                ("AI Consultant", "Отвечает на вопросы и уточняет запрос."),
                ("AI Search", "Подбирает услугу, тур, объект или товар по естественному запросу."),
                ("Recommendations", "Сужает выбор по параметрам клиента."),
                ("Lead Handoff", "Передаёт менеджеру контекст, а не пустой контакт."),
                ("Workflow Automation", "Запускает допустимые действия после консультации."),
            ],
            "price": "8–25M ₫ за типовой AI Consultant",
            "timeline": "ориентир 7–14 дней для одного канала и одной задачи",
            "offer": "ai-operator-pilot",
            "proof": ["max-tour"],
            "cta": "Показать AI на моём сценарии",
        },
        "en": {
            "name": "AI Operator",
            "label": "AI for sales & support",
            "headline": "An AI assistant that knows your offer and moves the customer to the next action.",
            "summary": "It answers within an approved scope, clarifies the request, recommends an option and passes context into a lead, booking or CRM.",
            "before": ["staff answer the same questions repeatedly", "customers struggle with a large catalogue", "after-hours enquiries wait until morning", "context is lost when handed to a person"],
            "after": ["AI answers from an approved knowledge base", "clarifies the request and helps choose", "passes structured context to the team", "complex cases escalate to a person"],
            "modules": [
                ("AI Consultant", "Answers questions and clarifies intent."),
                ("AI Search", "Finds services, tours, properties or products from natural-language requests."),
                ("Recommendations", "Narrows the options around customer parameters."),
                ("Lead Handoff", "Passes context instead of an empty contact."),
                ("Workflow Automation", "Triggers approved actions after the conversation."),
            ],
            "price": "8–25M ₫ for a typical AI Consultant",
            "timeline": "typically 7–14 days for one channel and one defined task",
            "offer": "ai-operator-pilot",
            "proof": ["max-tour"],
            "cta": "See AI on my scenario",
        },
    },
    "paybridge": {
        "ru": {
            "name": "PayBridge",
            "label": "Платежи и интеграционный слой",
            "headline": "Связывает checkout, оплату и подтверждённый статус с вашей бизнес-системой.",
            "summary": "Интеграционный слой между POS, сайтом или приложением и платёжным провайдером. Статус оплаты возвращается туда, где команда ведёт заказ.",
            "before": ["оплата и заказ живут в разных системах", "статус приходится проверять вручную", "webhook-события обрабатываются нестабильно", "сверка занимает время"],
            "after": ["один понятный payment flow", "подтверждённый статус возвращается в back-office", "ошибки и повторные события обрабатываются системно", "есть база для reconciliation и analytics"],
            "modules": [
                ("Payment integration", "Подключает оплату к booking или order flow."),
                ("POS middleware", "Связывает кассовый сценарий с платёжным контуром."),
                ("Webhooks", "Принимает и нормализует статусы."),
                ("Reconciliation", "Даёт основу для сверки транзакций."),
                ("API layer", "Передаёт события дальше в CRM, ERP или аналитику."),
            ],
            "price": "10–30M ₫ за типовую payment integration; middleware pilot — после технического scope",
            "timeline": "срок фиксируется после проверки POS, provider API и callback flow",
            "offer": "integration-sprint",
            "proof": ["max-tour"],
            "cta": "Обсудить технический пилот",
        },
        "en": {
            "name": "PayBridge",
            "label": "Платежи и интеграционный слой",
            "headline": "Connect checkout, payment and verified status back to your business system.",
            "summary": "An integration layer between POS, website or app and the payment provider. Confirmed payment status returns to the system where the team manages the order.",
            "before": ["payment and order live in separate systems", "staff verify payment manually", "webhook events are handled inconsistently", "reconciliation takes time"],
            "after": ["one clear payment flow", "verified status returns to back office", "errors and repeat events are handled systematically", "the data is ready for reconciliation and analytics"],
            "modules": [
                ("Payment integration", "Connects payment to the booking or order flow."),
                ("POS middleware", "Connects the checkout flow to the payment layer."),
                ("Webhooks", "Receives and normalises payment events."),
                ("Reconciliation", "Provides a basis for transaction matching."),
                ("API layer", "Passes events into CRM, ERP or analytics."),
            ],
            "price": "10–30M ₫ for a typical payment integration; middleware pilot after technical scoping",
            "timeline": "timeline is set after reviewing the POS, provider API and callback flow",
            "offer": "integration-sprint",
            "proof": ["max-tour"],
            "cta": "Discuss a technical pilot",
        },
    },
}

OFFERS = {
    "booking-start": {
        "product": "booking",
        "ru": {
            "name": "Booking Start",
            "headline": "Один законченный сценарий бронирования вместо ручной переписки.",
            "scope": ["выбор услуги", "дата или слот", "ключевые параметры", "создание брони", "подтверждение клиенту и команде"],
            "price": "8–18M ₫",
            "timeline": "ориентир 7–14 дней",
            "proof": "MAX TOUR, AVE Dental, PET NIKA, TRUE SURF",
            "cta": "Получить оценку Booking Start",
        },
        "en": {
            "name": "Booking Start",
            "headline": "One complete booking flow instead of manual back-and-forth.",
            "scope": ["service selection", "date or slot", "key parameters", "booking creation", "confirmation for customer and team"],
            "price": "8–18M ₫",
            "timeline": "typically 7–14 days",
            "proof": "MAX TOUR, AVE Dental, PET NIKA, TRUE SURF",
            "cta": "Get a Booking Start estimate",
        },
    },
    "mini-app-pilot": {
        "product": "online-sales",
        "ru": {
            "name": "Mini App Pilot",
            "headline": "Один рабочий клиентский сценарий внутри Telegram — без разработки большой системы целиком.",
            "scope": ["главный экран", "каталог или услуги", "одно ключевое действие", "адаптация под мобильный сценарий", "публичная рабочая версия"],
            "price": "10–12M ₫ за типовой первый запуск",
            "timeline": "7–10 дней",
            "proof": "AVE Dental, UNIQ SMART RENT, PET NIKA, TRUE SURF",
            "cta": "Оценить Mini App Pilot",
        },
        "en": {
            "name": "Mini App Pilot",
            "headline": "One customer journey inside Telegram without building the full product first.",
            "scope": ["home screen", "catalogue or services", "one primary action", "mobile flow adaptation", "public pilot"],
            "price": "10–12M ₫ for a typical pilot",
            "timeline": "7–10 days",
            "proof": "AVE Dental, UNIQ SMART RENT, PET NIKA, TRUE SURF",
            "cta": "Scope a Mini App pilot",
        },
    },
    "ai-operator-pilot": {
        "product": "ai-operator",
        "ru": {
            "name": "AI Operator Pilot",
            "headline": "Одна AI-задача, один канал и измеримый следующий шаг.",
            "scope": ["утверждённая база знаний", "сценарий вопросов", "правила ответа", "передача человеку или в заявку", "тестовый набор диалогов"],
            "price": "8–25M ₫",
            "timeline": "ориентир 7–14 дней",
            "proof": "MAX TOUR / AVE patterns",
            "cta": "Оценить AI Operator Pilot",
        },
        "en": {
            "name": "AI Operator Pilot",
            "headline": "One AI job, one channel and a measurable next action.",
            "scope": ["approved knowledge base", "question flow", "response rules", "human or lead handoff", "test conversation set"],
            "price": "8–25M ₫",
            "timeline": "typically 7–14 days",
            "proof": "MAX TOUR / AVE patterns",
            "cta": "Scope an AI Operator pilot",
        },
    },
    "operations-core": {
        "product": "operations",
        "ru": {
            "name": "Operations Core",
            "headline": "Одна рабочая система для клиентов, заказов и статусов команды.",
            "scope": ["основные сущности и статусы", "очередь клиентов/заказов", "ответственные", "admin/back-office", "базовая аналитика"],
            "price": "15–35M ₫",
            "timeline": "ориентир 2–4 недели",
            "proof": "MAX TOUR, PET NIKA, РИЦ",
            "cta": "Разобрать Operations Core",
        },
        "en": {
            "name": "Operations Core",
            "headline": "One operating flow for customers, orders and team status.",
            "scope": ["core entities and statuses", "customer/order queue", "ownership", "admin/back office", "basic analytics"],
            "price": "15–35M ₫",
            "timeline": "typically 2–4 weeks",
            "proof": "MAX TOUR, PET NIKA, RIC",
            "cta": "Scope an Operations Core",
        },
    },
    "integration-sprint": {
        "product": "paybridge",
        "ru": {
            "name": "Integration Sprint",
            "headline": "Один надёжный мост между двумя системами — с логами, статусами и обработкой ошибок.",
            "scope": ["разбор API/webhooks", "схема событий", "одна двусторонняя или односторонняя интеграция", "логи и ошибки", "документация для передачи"],
            "price": "по техническому scope",
            "timeline": "обычно 5–10 рабочих дней после доступа к API",
            "proof": "MAX TOUR / UNIQ integration patterns",
            "cta": "Обсудить Integration Sprint",
        },
        "en": {
            "name": "Integration Sprint",
            "headline": "One reliable bridge between two systems with logs, status and error handling.",
            "scope": ["API/webhook review", "event map", "one one-way or two-way flow", "logging and errors", "handoff documentation"],
            "price": "after technical scoping",
            "timeline": "typically 5–10 working days after API access",
            "proof": "MAX TOUR / UNIQ integration patterns",
            "cta": "Discuss an Integration Sprint",
        },
    },
}

INDUSTRIES = {
    "tourism": {
        "ru": {
            "name": "Туризм",
            "headline": "Онлайн-продажи и бронирование для экскурсионных компаний и туроператоров.",
            "lead": "Клиент выбирает экскурсию, дату и параметры сам; менеджер подключается там, где действительно нужен человек.",
            "problems": ["турист уточняет цену и места в чате", "ночные обращения ждут ответа", "брони из сайта и мессенджеров расходятся", "менеджер вручную переносит данные"],
            "path": ["Каталог и подбор", "Booking", "Оплата", "CRM / back-office", "AI-консультация при необходимости"],
            "entry": "Booking Start",
            "entry_slug": "booking-start",
            "proof": ["max-tour", "rusinfocenter"],
        },
        "en": {
            "name": "Tourism",
            "headline": "Online sales and booking for tour operators and activity companies.",
            "lead": "Customers choose the tour, date and parameters themselves; staff step in where a human is actually needed.",
            "problems": ["customers ask about price and availability in chat", "after-hours enquiries wait", "bookings from web and messengers are split", "staff copy details manually"],
            "path": ["Catalogue & selection", "Booking", "Payment", "CRM / back office", "AI assistance when useful"],
            "entry": "Booking Start",
            "entry_slug": "booking-start",
            "proof": ["max-tour", "rusinfocenter"],
        },
    },
    "rental": {
        "ru": {
            "name": "Аренда",
            "headline": "Каталог, доступность, цена и заявка для проката транспорта и других rental-бизнесов.",
            "lead": "Клиент выбирает объект и даты, видит понятные условия, а команда получает структурированный запрос вместо длинной переписки.",
            "problems": ["цены считают вручную", "доступность проверяют в чате", "заявки не связаны с парком", "статусы аренды ведутся отдельно"],
            "path": ["Каталог", "Расчёт цены", "Даты / доступность", "Заявка или Booking", "Operations"],
            "entry": "Catalog + Quote",
            "entry_slug": "mini-app-pilot",
            "proof": ["uniq-smart-rent"],
        },
        "en": {
            "name": "Rental",
            "headline": "Catalogue, availability, pricing and requests for vehicle and rental businesses.",
            "lead": "Customers choose the asset and dates, see clear terms and send a structured request instead of a long chat.",
            "problems": ["pricing is calculated manually", "availability is checked in chat", "requests are disconnected from inventory", "rental status is tracked elsewhere"],
            "path": ["Catalogue", "Price calculation", "Dates / availability", "Request or Booking", "Operations"],
            "entry": "Catalog + Quote",
            "entry_slug": "mini-app-pilot",
            "proof": ["uniq-smart-rent"],
        },
    },
    "clinics": {
        "ru": {
            "name": "Клиники",
            "headline": "Запись, клиентский кабинет и повторные обращения для медицинских и ветеринарных клиник.",
            "lead": "Пациент или владелец питомца проходит понятный путь до записи, а клиника получает структурированный контекст и может автоматизировать напоминания.",
            "problems": ["лид теряется до записи", "слот согласуется вручную", "повторный визит зависит от памяти администратора", "данные клиента разнесены по системам"],
            "path": ["Услуги и специалисты", "Booking", "Профиль клиента", "Напоминания", "CRM / повторные визиты"],
            "entry": "Mini App + Booking",
            "entry_slug": "booking-start",
            "proof": ["ave-dental", "pet-nika"],
        },
        "en": {
            "name": "Clinics",
            "headline": "Booking, customer account and repeat care for medical and veterinary clinics.",
            "lead": "Patients or pet owners follow a clear path to booking while the clinic receives structured context and can automate reminders.",
            "problems": ["leads drop before booking", "slots are arranged manually", "repeat visits depend on staff memory", "customer data is spread across systems"],
            "path": ["Services & specialists", "Booking", "Customer profile", "Reminders", "CRM / repeat visits"],
            "entry": "Mini App + Booking",
            "entry_slug": "booking-start",
            "proof": ["ave-dental", "pet-nika"],
        },
    },
}

INDUSTRY_CATALOG = {
    "ru": ["Туризм", "Аренда", "Клиники", "Beauty / SPA", "Hospitality", "Restaurants", "Retail", "Real Estate", "Education", "Events", "E-commerce", "Service business", "Logistics", "Manufacturing", "Telecom"],
    "en": ["Tourism", "Rental", "Clinics", "Beauty / SPA", "Hospitality", "Restaurants", "Retail", "Real Estate", "Education", "Events", "E-commerce", "Service business", "Logistics", "Manufacturing", "Telecom"],
}

TARGET_LANDINGS = {
    "tourism/booking": {
        "industry": "tourism", "product": "booking", "offer": "booking-start",
        "ru": {
            "title": "Автоматизация бронирования экскурсий",
            "headline": "Турист бронирует экскурсию сам. Менеджер получает готовый заказ.",
            "lead": "Выбор экскурсии, даты, количества людей и дополнительных параметров переносится из переписки в один понятный сценарий бронирования.",
            "specific": ["ночные заявки не ждут открытия офиса", "менеджер меньше времени тратит на одинаковые уточнения", "структура заказа сразу готова для рабочей панели"],
        },
        "en": {
            "title": "Tour booking automation",
            "headline": "The traveller books the tour; the team receives a complete order.",
            "lead": "Tour, date, party size and options move from chat into one structured booking flow.",
            "specific": ["after-hours enquiries do not wait for the office", "staff spend less time on repetitive clarification", "the order arrives ready for back office"],
        },
    },
    "tourism/ai-operator": {
        "industry": "tourism", "product": "ai-operator", "offer": "ai-operator-pilot",
        "ru": {
            "title": "AI-консультант для турагентства",
            "headline": "AI помогает туристу выбрать экскурсию и передаёт менеджеру уже понятный запрос.",
            "lead": "Консультант работает по вашему каталогу и правилам, задаёт уточняющие вопросы и ведёт к бронированию или человеку.",
            "specific": ["ответы по каталогу 24/7", "подбор по интересам, дате и составу группы", "передача контекста в Booking или менеджеру"],
        },
        "en": {
            "title": "AI assistant for tour companies",
            "headline": "AI helps the traveller choose and hands a clear request to the team.",
            "lead": "The assistant works from your catalogue and rules, asks clarifying questions and moves the customer to booking or a human.",
            "specific": ["catalogue answers 24/7", "recommendations by interest, date and party", "context passed to Booking or staff"],
        },
    },
    "rental/booking": {
        "industry": "rental", "product": "booking", "offer": "booking-start",
        "ru": {
            "title": "Бронирование для проката",
            "headline": "Клиент выбирает транспорт и даты без ручного расчёта в мессенджере.",
            "lead": "Каталог, период аренды, тариф и заявка соединяются в один сценарий; при необходимости добавляются депозит, CRM и обслуживание парка.",
            "specific": ["меньше вопросов «сколько стоит на эти даты?»", "заявка сразу содержит модель и период", "дальше можно связать с доступностью и рабочей панелью"],
        },
        "en": {
            "title": "Booking for rental businesses",
            "headline": "Customers choose the vehicle and dates without manual quoting in chat.",
            "lead": "Catalogue, rental period, pricing and request work as one flow; deposit, CRM and fleet operations can be added later.",
            "specific": ["fewer repetitive price questions", "the request already contains model and dates", "availability and back office can connect later"],
        },
    },
    "clinics/booking": {
        "industry": "clinics", "product": "booking", "offer": "booking-start",
        "ru": {
            "title": "Онлайн-запись для клиники",
            "headline": "Пациент выбирает услугу и время, администратор получает структурированную запись.",
            "lead": "Booking можно связать с врачами, услугами, напоминаниями и клиентским кабинетом — без полной замены текущей системы клиники.",
            "specific": ["меньше ручного согласования времени", "контекст пациента приходит вместе с записью", "напоминания снижают долю забытых визитов"],
        },
        "en": {
            "title": "Online booking for clinics",
            "headline": "Patients choose the service and time; the clinic receives a structured booking.",
            "lead": "Booking can connect to doctors, services, reminders and customer accounts without replacing the clinic's entire system.",
            "specific": ["less manual slot coordination", "patient context arrives with the booking", "reminders reduce forgotten appointments"],
        },
    },
    "clinics/ai-operator": {
        "industry": "clinics", "product": "ai-operator", "offer": "ai-operator-pilot",
        "ru": {
            "title": "AI-консультант для клиники",
            "headline": "AI отвечает на типовые вопросы и помогает довести обращение до записи.",
            "lead": "Работает только по утверждённой информации о клинике и услугах, не заменяя врача и не выдавая медицинских заключений.",
            "specific": ["режим работы, услуги, подготовка и общая информация", "уточнение нужной услуги", "handoff администратору с контекстом"],
        },
        "en": {
            "title": "AI assistant for clinics",
            "headline": "AI handles routine questions and helps move the enquiry toward booking.",
            "lead": "It uses approved clinic and service information only; it does not replace a clinician or provide medical diagnosis.",
            "specific": ["hours, services, preparation and general information", "clarifies which service the customer needs", "hands context to clinic staff"],
        },
    },
    "restaurants/paybridge": {
        "industry": None, "product": "paybridge", "offer": "integration-sprint",
        "ru": {
            "title": "Payment middleware для ресторанов и POS",
            "headline": "Свяжите checkout и подтверждённый статус оплаты без ручной сверки.",
            "lead": "PayBridge подходит POS-вендорам, интеграторам и сетям, которым нужно надёжно связать кассовый сценарий с платёжным провайдером.",
            "specific": ["статус оплаты возвращается в кассовый сценарий", "webhook-события обрабатываются системно", "есть основа для reconciliation и rollout на сеть"],
        },
        "en": {
            "title": "Payment middleware for restaurants and POS",
            "headline": "Connect checkout and verified payment status without manual reconciliation.",
            "lead": "PayBridge is for POS vendors, integrators and chains that need a controlled payment flow between checkout and provider.",
            "specific": ["payment status returns to the checkout flow", "webhook events are handled systematically", "ready for reconciliation and multi-location rollout"],
        },
    },
}

CASES = {
    "max-tour": {
        "ru": {"name": "MAX TOUR", "industry": "Туризм", "status": "working-demo", "status_label": "РАБОЧЕЕ ДЕМО", "summary": "Клиентский путь, бронирование, роли, admin и owner analytics для экскурсионного бизнеса.", "shows": ["Booking", "Operations", "AI"], "demo": "https://max-tour.viiversion.com/"},
        "en": {"name": "MAX TOUR", "industry": "Tourism", "status": "working-demo", "status_label": "WORKING DEMO", "summary": "Customer flow, booking, roles, admin and owner analytics for a tour business.", "shows": ["Booking", "Operations", "AI"], "demo": "https://max-tour.viiversion.com/"},
    },
    "uniq-smart-rent": {
        "ru": {"name": "UNIQ SMART RENT", "industry": "Аренда", "status": "working-demo", "status_label": "РАБОЧЕЕ ДЕМО", "summary": "Каталог, pricing и request lifecycle для аренды транспорта.", "shows": ["Online Sales", "Booking", "Operations"], "demo": "https://uniq-smart-rent.mirozdanie6v.workers.dev/"},
        "en": {"name": "UNIQ SMART RENT", "industry": "Rental", "status": "working-demo", "status_label": "WORKING DEMO", "summary": "Catalogue, pricing and request lifecycle for vehicle rental.", "shows": ["Online Sales", "Booking", "Operations"], "demo": "https://uniq-smart-rent.mirozdanie6v.workers.dev/"},
    },
    "pet-nika": {
        "ru": {"name": "PET NIKA", "industry": "Veterinary", "status": "prototype", "status_label": "ПУБЛИЧНЫЙ ПРОТОТИП", "summary": "Клиентский кабинет, питомцы, обращения, booking и admin-слой.", "shows": ["Online Sales", "Booking", "Operations"], "demo": "https://pet-nika.viiversion.com/"},
        "en": {"name": "PET NIKA", "industry": "Veterinary", "status": "prototype", "status_label": "PUBLIC PROTOTYPE", "summary": "Customer account, pets, requests, booking and admin layer.", "shows": ["Online Sales", "Booking", "Operations"], "demo": "https://pet-nika.viiversion.com/"},
    },
    "ave-dental": {
        "ru": {"name": "AVE Dental", "industry": "Dental", "status": "prototype", "status_label": "ПУБЛИЧНЫЙ ПРОТОТИП", "summary": "Мультиязычный Mini App и booking-flow для клиники.", "shows": ["Online Sales", "Booking"], "demo": "https://ave-dental-miniapp.vercel.app/"},
        "en": {"name": "AVE Dental", "industry": "Dental", "status": "prototype", "status_label": "PUBLIC PROTOTYPE", "summary": "Multilingual Mini App and booking flow for a clinic.", "shows": ["Online Sales", "Booking"], "demo": "https://ave-dental-miniapp.vercel.app/"},
    },
    "rusinfocenter": {
        "ru": {"name": "Русский Информационный Центр", "industry": "Туризм", "status": "concept", "status_label": "КЛИЕНТСКАЯ КОНЦЕПЦИЯ", "summary": "Цифровой клиентский путь и архитектура будущей системы продаж.", "shows": ["Online Sales", "Booking", "Integrations"], "demo": "https://rusinfocenter.viiversion.com/"},
        "en": {"name": "Russian Information Center", "industry": "Tourism", "status": "concept", "status_label": "CLIENT CONCEPT", "summary": "Customer journey and architecture for a future sales system.", "shows": ["Online Sales", "Booking", "Integrations"], "demo": "https://rusinfocenter.viiversion.com/"},
    },
    "g-beauty": {
        "ru": {"name": "G-Beauty", "industry": "Beauty", "status": "prototype", "status_label": "ПУБЛИЧНЫЙ ПРОТОТИП", "summary": "Landing, Mini App, booking и demo admin для локального beauty-бизнеса.", "shows": ["Online Sales", "Booking", "Operations"], "demo": "https://gbeauty-vien-trieu-prototype.mirozdanie6v.workers.dev/"},
        "en": {"name": "G-Beauty", "industry": "Beauty", "status": "prototype", "status_label": "PUBLIC PROTOTYPE", "summary": "Landing, Mini App, booking and demo admin for a local beauty business.", "shows": ["Online Sales", "Booking", "Operations"], "demo": "https://gbeauty-vien-trieu-prototype.mirozdanie6v.workers.dev/"},
    },
    "true-surf": {
        "ru": {"name": "TRUE SURF", "industry": "Activities", "status": "prototype", "status_label": "ПУБЛИЧНЫЙ ПРОТОТИП", "summary": "Booking, client passport и repeat-flow в формате Mini App.", "shows": ["Online Sales", "Booking"], "demo": "https://truesurf-app.viiversion.com/"},
        "en": {"name": "TRUE SURF", "industry": "Activities", "status": "prototype", "status_label": "PUBLIC PROTOTYPE", "summary": "Booking, client passport and repeat flow in a Mini App.", "shows": ["Online Sales", "Booking"], "demo": "https://truesurf-app.viiversion.com/"},
    },
}

LABS = {
    "proposal-studio": {
        "ru": {"name": "Proposal Studio", "status": "ДОСТУПНО", "summary": "Research → diagnosis → solution → commercial proposal → QA.", "url": "/proposal-studio/"},
        "en": {"name": "Proposal Studio", "status": "AVAILABLE", "summary": "Research → diagnosis → solution → commercial proposal → QA.", "url": "/proposal-studio/"},
    },
    "mini-app-factory": {
        "ru": {"name": "Mini App Factory", "status": "ЗАКРЫТАЯ БЕТА", "summary": "White-label production line для серийной сборки клиентских Mini Apps.", "url": None},
        "en": {"name": "Mini App Factory", "status": "PRIVATE BETA", "summary": "A white-label production line for repeatable client Mini App delivery.", "url": None},
    },
    "zl-web-agent": {
        "ru": {"name": "ZL Web Agent", "status": "ЗАКРЫТАЯ БЕТА", "summary": "Evidence-based аудит WordPress и план безопасных изменений.", "url": None},
        "en": {"name": "ZL Web Agent", "status": "PRIVATE BETA", "summary": "Evidence-based WordPress audit and a safe change plan.", "url": None},
    },
    "video-human-editor": {
        "ru": {"name": "Event Video Human Editor", "status": "В РАЗРАБОТКЕ", "summary": "Семантический анализ больших массивов event-video до ручного монтажа.", "url": None},
        "en": {"name": "Event Video Human Editor", "status": "IN DEVELOPMENT", "summary": "Semantic analysis of large event-video collections before human editing.", "url": None},
    },
}

TEAM = {
    "ru": [
        ("Дмитрий Владимиров", "Systems architecture · databases · integrations · development", "Oracle, PL/SQL, ETL, Linux, API, telecom BSS / Revenue Assurance. Опыт сложных систем для международных и телеком-проектов."),
        ("Ольга Ногтич", "Product · UX/UI · research · content", "Продуктовая логика, интерфейсы, пользовательские сценарии, исследования и визуальные коммуникации."),
    ],
    "en": [
        ("Dmitrii Vladimirov", "Systems architecture · databases · integrations · development", "Oracle, PL/SQL, ETL, Linux, API, telecom BSS / Revenue Assurance. Experience with complex telecom and international systems."),
        ("Olga Nogtich", "Product · UX/UI · research · content", "Product logic, interfaces, customer journeys, research and visual communication."),
    ],
}

NAV = {
    "ru": [("Решения", "/solutions/"), ("Продукты", "/products/"), ("Кейсы", "/cases/"), ("Enterprise", "/enterprise/"), ("Компания", "/about/")],
    "en": [("Solutions", "/solutions/"), ("Products", "/products/"), ("Cases", "/cases/"), ("Enterprise", "/enterprise/"), ("Company", "/about/")],
}
